name: MultiServerCommands
author: Pijok
version: 1.0.0
api-version: 1.16
main: pl.pijok.multiservercommands.MultiServerCommands
commands:
  multiservercommand:
    usage: /multiservercommand
    aliases: [msc]